version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realestate-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"  # Backend
      - "3001:3001"  # Frontend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: realestate
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
    networks:
      - realestate_network

  postgres:
    image: postgres:15
    container_name: postgres-15
    restart: always
    environment:
      POSTGRES_DB: realestate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - realestate_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d realestate"]
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  realestate_network:
    driver: bridge

volumes:
  postgres_data: