version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-15
    restart: always
    environment:
      POSTGRES_DB: realestate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - realestate_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d realestate"]
      interval: 5s
      timeout: 2s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    container_name: realestate-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: realestate
      NODE_ENV: development
    volumes:
      - ./src:/app
      - /app/node_modules
    networks:
      - realestate_network
    restart: unless-stopped
    
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    container_name: realestate-frontend
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api  # For Docker-to-Docker communication
      NEXT_PUBLIC_API_URL_LOCAL: http://localhost:3000/api  # For local development
      PORT: 3001
    volumes:
      - ./UI:/app
      - /app/node_modules
      - /app/.next
    networks:
      - realestate_network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  realestate_network:
    driver: bridge

volumes:
  postgres_data: